# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Falu < Formula
  desc "Falu CLI"
  homepage "https://falu.io"
  license "MIT"
  version "#{BINARIES_VERSION}#"

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/faluapp/falu-cli/releases/download/#{BINARIES_VERSION}#/falu-#{BINARIES_VERSION}#-linux-arm64.tar.gz"
      sha256 "#{LINUX_ARM64_BINARY_SHA256}#"
    end

    if Hardware::CPU.intel?
      url "https://github.com/faluapp/falu-cli/releases/download/#{BINARIES_VERSION}#/falu-#{BINARIES_VERSION}#-linux-x64.tar.gz"
      sha256 "#{LINUX_X64_BINARY_SHA256}#"
    end
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/faluapp/falu-cli/releases/download/#{BINARIES_VERSION}#/falu-#{BINARIES_VERSION}#-osx-arm64.tar.gz"
      sha256 "#{MACOS_ARM64_BINARY_SHA256}#"
    end

    if Hardware::CPU.intel?
      url "https://github.com/faluapp/falu-cli/releases/download/#{BINARIES_VERSION}#/falu-#{BINARIES_VERSION}#-osx-x64.tar.gz"
      sha256 "#{MACOS_X64_BINARY_SHA256}#"
    end
  end

  def install
    bin.install "falu"
  end

  test do
    system "#{bin}/falu", "--version"
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the Falu CLI! If this is your first time using the CLI, be sure to run `falu login` first.
  EOS
  end
end