name: Build

on:
  push:
    # branches:
    # - main
    tags:
    - '*'
    paths-ignore:
    - README.md
    - LICENSE
    - CHANGELOG.md
    - docs/**
  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md
    - LICENSE
    - CHANGELOG.md
    - docs/**
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the action'
        required: false
        default: 'Pre-Release'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  PKG_NAME: 'falu'
  PKG_DESCRIPTION: 'Falu CLI'
  PKG_MAINTAINER: 'Falu <support@falu.io>'
  PKG_HOMEPAGE: 'https://falu.io'
  PKG_VENDOR: FALU TECHNOLOGIES LIMITED
  PKG_LICENSE: MIT

jobs:
  Build:
    strategy:
      fail-fast: true
      matrix:
        os: [ 'macos', 'ubuntu', 'windows']
        arch: [ 'x64', 'arm64' ]
        include:
        - { os: ubuntu, arch: x64, deb-arch: amd64, rpm-arch: x86_64 }
        - { os: ubuntu, arch: arm64, deb-arch: arm64, rpm-arch: aarch64 }
        # list of RIDs (Runtime Identifiers) can be found at:
        # https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json
        - { os: ubuntu, rid-prefix: 'linux' }
        - { os: windows, rid-prefix: 'win' }
        - { os: macos, rid-prefix: 'osx' }
        # macos-latest uses macos-12 which fails to build the app (macos-13 works)
        - { os: macos, runs-on: 'macos-13' } # macos-latest
        - { os: windows, archive-type: 'zip' } # windows creates zip files, others default to 'tar'

    runs-on: ${{ matrix.runs-on || format('{0}-{1}', matrix.os, 'latest') }}

    env:
      DOTNET_RID: ${{ format('{0}-{1}', matrix.rid-prefix, matrix.arch) }}
      GITVERSION_NUGETVERSIONV2: 'overriden by gitversion action'
      GITVERSION_MAJORMINORPATCH: 'overriden by gitversion action'

    outputs:
      BINARIES_VERSION: ${{ steps.gitversion.outputs.nuGetVersionV2 }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for GitVersion
        submodules: true

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      id: gitversion
      with:
        useConfigFile: true

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore --runtime ${{ env.DOTNET_RID }} -v detailed

    - name: Build
      if: github.event_name == 'pull_request'
      run: dotnet build --configuration Release --no-restore

    - name: Test
      if: github.event_name == 'pull_request'
      run: dotnet test --configuration Release --no-build --collect "Code coverage"

    - name: Publish
      run: >
        dotnet publish
        -p:PublishSingleFile=true
        -p:DebugType=None
        -p:DebugSymbols=false
        -p:PublishTrimmed=true
        -p:AssemblyName=falu
        --runtime ${{ env.DOTNET_RID }}
        --configuration Release
        --output ${{ github.workspace }}/drop/${{ env.DOTNET_RID }}
        --self-contained true
        --no-restore
        src/FaluCli/FaluCli.csproj

    - name: Test (CLI) # ensure the CLI can launch (catches global DI issues)
      # ARM runners are in preview and we cannot use them, so we skip this test
      # https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/
      # TODO: consider using QEMU emulator for ARM?
      if: ${{ !contains(matrix.arch, 'arm') }}
      run: ./falu logout
      working-directory: ${{ github.workspace }}/drop/${{ env.DOTNET_RID }}

    - name: Publish Artifact (drop)
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/drop/**
        name: drop-${{ env.DOTNET_RID }}

    - name: Create Archive Folder
      run: mkdir ${{ github.workspace }}/releases

    - name: Create Archive (${{ matrix.archive-type || 'tar.gz' }})
      uses: thedoctor0/zip-release@master
      with:
        type: ${{ matrix.archive-type || 'tar' }}
        filename: ${{ github.workspace }}/releases/falu-${{ env.GITVERSION_NUGETVERSIONV2 }}-${{ env.DOTNET_RID }}.${{ matrix.archive-type || 'tar.gz' }}
        directory: ${{ github.workspace }}/drop/${{ env.DOTNET_RID }}

    - name: Prepare .debpkg and .rpmpkg
      if: ${{ matrix.deb-arch || matrix.rpm-arch }}
      run: |
        mkdir -p .debpkg/usr/bin
        cp -p ${{ github.workspace }}/drop/${{ env.DOTNET_RID }}/* .debpkg/usr/bin/

        mkdir -p .rpmpkg/usr/bin
        cp -p ${{ github.workspace }}/drop/${{ env.DOTNET_RID }}/* .rpmpkg/usr/bin/

    - name: 'Build DEB package'
      uses: jiro4989/build-deb-action@v3
      if: ${{ matrix.deb-arch }}
      with:
        desc: '${{ env.PKG_DESCRIPTION }}'
        maintainer: ${{ env.PKG_MAINTAINER }}
        version: ${{ env.GITVERSION_NUGETVERSIONV2 }}
        package: ${{ env.PKG_NAME }}
        package_root: .debpkg
        arch: '${{ matrix.deb-arch}}'

    - name: 'Build RPM package'
      uses: jiro4989/build-rpm-action@v2
      if: ${{ matrix.rpm-arch }}
      with:
        summary: '${{ env.PKG_DESCRIPTION }}'
        desc: '${{ env.PKG_DESCRIPTION }}'
        maintainer: ${{ env.PKG_MAINTAINER }}
        vendor: ${{ env.PKG_VENDOR }}
        license: ${{ env.PKG_LICENSE }}
        version: ${{ env.GITVERSION_MAJORMINORPATCH }}
        package: ${{ env.PKG_NAME }}
        package_root: .rpmpkg
        arch: '${{ matrix.rpm-arch}}'

    - name: Rename deb and rpm packages
      if: ${{ matrix.deb-arch || matrix.rpm-arch }}
      run: |
        src=falu_${{ env.GITVERSION_NUGETVERSIONV2 }}_${{ matrix.deb-arch}}.deb
        dest=${{ github.workspace }}/releases/falu-${{ env.GITVERSION_NUGETVERSIONV2 }}-linux-${{ matrix.deb-arch}}.deb
        mv $src $dest

        src=falu-${{ env.GITVERSION_MAJORMINORPATCH }}-1.el7.${{ matrix.rpm-arch}}.rpm
        dest=${{ github.workspace }}/releases/falu-${{ env.GITVERSION_NUGETVERSIONV2 }}-linux-${{ matrix.rpm-arch}}.rpm
        mv $src $dest

    - name: Publish Artifact (releases)
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/releases/**
        name: releases-${{ env.DOTNET_RID }}

    - name: Test (DEB)
      # TODO: test DEB package for ARM once we have ARM runners
      # https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/
      # if: ${{ matrix.deb-arch }}
      if: ${{ matrix.deb-arch && matrix.arch == 'x64' }}
      run: |
        sudo apt-get install -y -f \
        ${{ github.workspace }}/releases/falu-${{ env.GITVERSION_NUGETVERSIONV2 }}-linux-${{ matrix.deb-arch}}.deb

    - name: Test (RPM)
      # TODO: test RPM package for ARM once we have ARM runners
      # https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/
      # if: ${{ matrix.rpm-arch }}
      if: ${{ matrix.rpm-arch && matrix.arch == 'x64' }}
      run: |
        sudo apt-get install alien
        sudo alien -i \
        ${{ github.workspace }}/releases/falu-${{ env.GITVERSION_NUGETVERSIONV2 }}-linux-${{ matrix.rpm-arch}}.rpm

  Checksum:
    runs-on: ubuntu-latest
    needs: [ Build ]

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        path: releases
        pattern: releases-*
        merge-multiple: true

    - name: Generate checksum
      uses: jmgilman/actions-generate-checksum@v1
      with:
        method: 'sha256'
        output: 'checksum.txt'
        patterns: |
          releases/falu-*.deb
          releases/falu-*.rpm
          releases/falu-*.tar.gz
          releases/falu-*.zip

    # retain only the file names
    # waiting on https://github.com/jmgilman/actions-generate-checksum/pull/2
    - name: Strip directory
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "releases/falu-"
        replace: "falu-"
        include: checksum.txt

    - name: Publish Artifact (releases)
      uses: actions/upload-artifact@v4
      with:
        path: checksum.txt
        name: releases-checksum

  Packaging:
    runs-on: macos-latest
    needs: [ Build ]
    outputs:
      BINARIES_VERSION: ${{ needs.Build.outputs.BINARIES_VERSION }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        path: ${{ github.workspace }}/releases
        pattern: releases-*
        merge-multiple: true

    - name: Prepare templates
      run: |
        mkdir -p ${{ github.workspace }}/generated/homebrew/
        mv packaging/homebrew/formula-template.rb ${{ github.workspace }}/generated/homebrew/falu.rb
        mkdir -p ${{ github.workspace }}/generated/scoop/
        mv packaging/scoop/bucket-template.json ${{ github.workspace }}/generated/scoop/falu.json

    - name: Prepare variables
      working-directory: ${{ github.workspace }}/releases
      run: |
        echo "BINARIES_VERSION=$BINARIES_VERSION" >> "$GITHUB_ENV"

        checksumMacARM64=$(shasum -a 256 falu-$BINARIES_VERSION-osx-arm64.tar.gz | cut -d " " -f 1)
        checksumMacX64=$(shasum -a 256 falu-$BINARIES_VERSION-osx-x64.tar.gz | cut -d " " -f 1)
        checksumLinuxARM64=$(shasum -a 256 falu-$BINARIES_VERSION-linux-arm64.tar.gz | cut -d " " -f 1)
        checksumLinuxX64=$(shasum -a 256 falu-$BINARIES_VERSION-linux-x64.tar.gz | cut -d " " -f 1)
        checksumWindowsARM64=$(shasum -a 256 falu-$BINARIES_VERSION-win-arm64.zip | cut -d " " -f 1)
        checksumWindowsX64=$(shasum -a 256 falu-$BINARIES_VERSION-win-x64.zip | cut -d " " -f 1)
        echo "MACOS_ARM64_BINARY_SHA256=$checksumMacARM64" >> "$GITHUB_ENV"
        echo "MACOS_X64_BINARY_SHA256=$checksumMacX64" >> "$GITHUB_ENV"
        echo "LINUX_ARM64_BINARY_SHA256=$checksumLinuxARM64" >> "$GITHUB_ENV"
        echo "LINUX_X64_BINARY_SHA256=$checksumLinuxX64" >> "$GITHUB_ENV"
        echo "WINDOWS_ARM64_BINARY_SHA256=$checksumWindowsARM64" >> "$GITHUB_ENV"
        echo "WINDOWS_X64_BINARY_SHA256=$checksumWindowsX64" >> "$GITHUB_ENV"
      env:
        BINARIES_VERSION: ${{ needs.Build.outputs.BINARIES_VERSION }}

    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["${{ github.workspace }}/generated/homebrew/falu.rb","${{ github.workspace }}/generated/scoop/falu.json"]'

    - name: Publish Artifact (releases)
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/generated
        name: releases-generated

  Release:
    runs-on: ubuntu-latest
    needs: [ Checksum, Packaging ]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        path: ${{ github.workspace }}/releases
        pattern: releases-*
        merge-multiple: true

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        # comma-separated values ('>' will make it a single line)
        artifacts: >
          ${{ github.workspace }}/releases/checksum.txt,
          ${{ github.workspace }}/releases/falu-*.deb,
          ${{ github.workspace }}/releases/falu-*.rpm,
          ${{ github.workspace }}/releases/falu-*.tar.gz,
          ${{ github.workspace }}/releases/falu-*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        allowUpdates: true

    - name: Update homebrew tap repository
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.RELEASING_GITHUB_TOKEN }}
      with:
        source_file: '${{ github.workspace }}/releases/homebrew/falu.rb'
        destination_repo: 'faluapp/homebrew-falu-cli'
        user_email: 'support@falu.io'
        user_name: 'falu-ci'
        commit_message: 'Update homebrew tap to ${{ needs.Packaging.outputs.BINARIES_VERSION }}'

    - name: Update scoop bucket repository
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.RELEASING_GITHUB_TOKEN }}
      with:
        source_file: '${{ github.workspace }}/releases/scoop/falu.json'
        destination_repo: 'faluapp/scoop-falu-cli'
        user_email: 'support@falu.io'
        user_name: 'falu-ci'
        commit_message: 'Update scoop bucket to ${{ needs.Packaging.outputs.BINARIES_VERSION }}'
