name: Build and Publish

on:
  push:
    # branches:
    #   - main
    tags:
      - '*'
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the action'
        required: false
        default: 'Pre-Release'

jobs:
  Build:
    strategy:
      fail-fast: true
      matrix:
        config:
          - rid: linux-x64
            os: ubuntu-latest
          - rid: win-x64
            os: ubuntu-latest #windows-latest
          - rid: osx-x64
            os: ubuntu-latest #macos-latest

    runs-on: ${{ matrix.config.os }}
    env:
      buildConfiguration: 'Release'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      RELEASING_SDK: false # ensure the SDK is not built for release
      RELEASING_CLI: true # enables

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Required for GitVersion
        submodules: true

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore --runtime ${{ matrix.config.rid }}

    - name: Publish
      run: >
        dotnet publish
        --runtime ${{ matrix.config.rid }}
        --configuration $buildConfiguration
        --output $GITHUB_WORKSPACE/drop/${{ matrix.config.rid }}
        --self-contained true
        --no-restore
        src/FaluCli/FaluCli.csproj

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/drop/**
        name: drop
